#!/usr/bin/env python3
"""Build the composition from SCRIPT.md, audio_meta.json, stage.html and frames/NN-slug.html.

Writes compositions/frames/*.html, compositions/captions.html and index.html. Do not edit those files;
edit the sources and run build.py again. Run it in the project directory.
"""
import json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import read_script, frame_id, load_meta

SKILL = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GSAP = "https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"
GSAP_SRI = "sha384-sG0Hv1tP1lZCk9KQmrIbY/XNwi+OY84GQqhMscbnsoBFqAz8KNCil1kvfL3Hbbk2"
FADE = 0.5  # crossfade between frames; each frame runs FADE past the start of the next

meta, sections = read_script()
m = load_meta()
voices = m["voices"]
if [v["text"] for v in voices] != [s["text"] for s in sections]:
    bad = [s["n"] for s, v in zip(sections, voices) if s["text"] != v["text"]] or ["count"]
    sys.exit(f"SCRIPT.md differs from audio_meta.json in section(s) {bad}. Run section.py <n> first.")

kit_css = open(f"{SKILL}/kit/kit.css").read()
kit_js = open(f"{SKILL}/kit/kit.js").read()
stage = open("stage.html").read() if os.path.exists("stage.html") else ""


def cs(x):  # seconds -> centiseconds; all timing sums are in integers, so no float overlaps
    return int(round(x * 100))


def sec(c):
    return f"{c / 100:g}"


def norm(t):
    return re.sub(r"[^a-z0-9]+", "", t.lower())



def design_warnings(name, html):
    """Kit design rules that a script can check: grid snapping and text size."""
    out = []
    els = [set(c.split()) for c in re.findall(r'class="([^"]*)"', html)]
    for sel, body in re.findall(r"([^{}<>]+)\{([^{}]*)\}", "".join(re.findall(r"<style>(.*?)</style>", html, re.S))):
        cls = set(re.findall(r"\.([\w-]+)", sel))
        if not cls or any(c.startswith("k-") for c in cls):
            continue
        used = set().union(*[e for e in els if e & cls]) if any(e & cls for e in els) else set()
        box = bool(used & {"k-box", "k-dash"})
        grid = 40 if box else 20
        for prop, v in re.findall(r"(?<![\w-])(left|top|width|height|font-size)\s*:\s*(-?[\d.]+)px", body):
            v = float(v)
            if prop == "font-size":
                if v < 28 and not used & {"k-label", "k-tag"}:
                    out.append(f"{name}: {sel.strip()} font-size {v:g}px; content text is 28 px or more")
            elif v % grid:
                out.append(f"{name}: {sel.strip()} {prop} {v:g}px is not on the {grid} px grid" + (" (boxes snap to 40)" if box else ""))
    return out

starts, total = [], 0
for v in voices:
    starts.append(total); total += cs(v["duration_s"])

# frames
os.makedirs("compositions/frames", exist_ok=True)
warnings = design_warnings("stage.html", stage)
missing = [f"frames/{frame_id(s)}.html" for s in sections if not os.path.exists(f"frames/{frame_id(s)}.html")]
if missing:
    sys.exit("Missing frame sources: " + ", ".join(missing))
for s, v in zip(sections, voices):
    fid = frame_id(s)
    src = open(f"frames/{fid}.html").read()
    scripts = re.findall(r"<script>(.*?)</script>", src, re.S)
    if len(scripts) != 1:
        sys.exit(f"frames/{fid}.html: needs exactly one <script> with the cues")
    body = re.sub(r"<script>.*?</script>", "", src, flags=re.S).strip()
    use_stage = "<!-- no-stage -->" not in src
    dur = cs(v["duration_s"]) + (cs(FADE) if s["n"] < len(sections) else 0)
    words = json.dumps([[norm(w["text"]), w["start"]] for w in v["words"] if norm(w["text"])], separators=(",", ":"))
    # footnotes: [id, time of the word that the marker follows]; texts of all footnotes for data-note
    notes = json.dumps({"at": [[i, v["words"][j]["start"]] for i, j in s["notes"]], "text": meta["notes"]}, separators=(",", ":"))
    out = f"""<template>
  <!-- generated by build.py from frames/{fid}.html and stage.html; do not edit -->
  <style>
{kit_css}  </style>
  <div id="root" data-composition-id="{fid}" data-start="0" data-duration="{sec(dur)}" data-width="1920" data-height="1080">
    <div class="k-ground"></div>
    <div class="k-hair k-hair-top"></div>
    <div class="k-hair k-hair-bot"></div>
{stage if use_stage else ""}
{body}
  </div>
  <script src="{GSAP}"></script>
  <script>
    (function () {{
{kit_js}
      var k = Kit.frame("{fid}", {words}, {notes});
{scripts[0].strip()}
      k.done();
    }})();
  </script>
</template>
"""
    open(f"compositions/frames/{fid}.html", "w").write(out)
    warnings += design_warnings(f"frames/{fid}.html", src)

# captions: break after punctuation, after 3 words, or at a pause
groups = []
for s, v, st in zip(sections, voices, starts):
    cur = []
    for i, w in enumerate(v["words"]):
        cur.append(w)
        nxt = v["words"][i + 1] if i + 1 < len(v["words"]) else None
        if not nxt or re.search(r"[.,:;?!]$", w["text"]) or len(cur) == 3 or nxt["start"] - w["end"] > 0.35:
            g = len(groups)
            groups.append({"id": f"caption-group-{g}", "frame": s["n"], "start": round(st / 100 + cur[0]["start"], 2),
                           "end": round(st / 100 + cur[-1]["end"], 2), "text": " ".join(x["text"] for x in cur),
                           "words": [{"id": f"caption-word-{g}-{j}", "text": x["text"], "start": round(st / 100 + x["start"], 2),
                                      "end": round(st / 100 + x["end"], 2)} for j, x in enumerate(cur)]})
            cur = []
cap = open(f"{SKILL}/templates/captions.html").read()
cap = cap.replace("__GROUPS__", json.dumps(groups, separators=(",", ":"))).replace("__DURATION__", sec(total))
open("compositions/captions.html", "w").write(cap)

# index
clips, fades = [], []
for i, (s, v) in enumerate(zip(sections, voices)):
    fid, st = frame_id(s), starts[i]
    dur = cs(v["duration_s"]) + (cs(FADE) if i + 1 < len(sections) else 0)
    clips.append(f'      <div id="el-{fid}" class="scene" data-composition-id="{fid}" data-composition-src="compositions/frames/{fid}.html" data-start="{sec(st)}" data-duration="{sec(dur)}" data-track-index="{i % 2}"></div>\n'
                 f'      <audio id="el-{fid}-voice" src="{v["path"]}" data-start="{sec(st)}" data-duration="{sec(cs(v["duration_s"]))}" data-track-index="10" data-volume="1"></audio>')
    if i:
        prev = frame_id(sections[i - 1])
        fades.append(f'        tl.to("#el-{prev}", {{ opacity: 0, duration: {FADE}, ease: "power2.inOut" }}, {sec(st)});\n'
                     f'        tl.fromTo("#el-{fid}", {{ opacity: 0 }}, {{ opacity: 1, duration: {FADE}, ease: "power2.inOut" }}, {sec(st)});')
nl = "\n"
index = f"""<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1920, height=1080">
    <!-- generated by build.py; do not edit -->
    <script src="{GSAP}" integrity="{GSAP_SRI}" crossorigin="anonymous"></script>
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ width: 1920px; height: 1080px; overflow: hidden; background: #000; }}
      #root {{ position: relative; width: 1920px; height: 1080px; overflow: hidden; background: #f0ebde; }}
      .scene {{ position: absolute; inset: 0; width: 100%; height: 100%; }}
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="{sec(total)}" data-width="1920" data-height="1080">
{(nl + nl).join(clips)}

      <div id="el-captions" data-track-kind="captions" class="scene" data-composition-id="captions" data-composition-src="compositions/captions.html" data-start="0" data-duration="{sec(total)}" data-track-index="2"></div>
    </div>
    <script>
      window.__timelines = window.__timelines || {{}};
      window.__timelines["main"] = gsap.timeline({{ paused: true }});
      (function () {{
        var tl = window.__timelines["main"];
{nl.join(fades)}
        tl.to({{}}, {{ duration: {sec(total)} }}, 0);
      }})();
    </script>
  </body>
</html>
"""
open("index.html", "w").write(index)
print(f"{len(sections)} frames, {len(groups)} caption groups, {total / 100:.2f}s")
for w in warnings:
    print("design:", w)
# review: each frame when its narration ends, so all its objects are on screen
ends = [f"{(st + cs(v['words'][-1]['end'])) / 100:.2f}" for st, v in zip(starts, voices)]
print("review: npx hyperframes snapshot --at " + ",".join(ends))
